import { ISearch } from '../../../common/models/common';
import { Moment } from 'moment';

export interface ICiscoIB {
  id?: number;
  tenant_id: number;
  company_id?: number;
  bu_id?: number;
  source?: string;
  customer_name?: string;
  asset_id?: string;
  unique_record?: string;
  duplicate_record?: string;
  duplicate_coverage?: string;
  zone_assignment?: string;
  zone_description?: string;
  serial_number?: string;
  instance_number?: number;
  parent_serial_number?: string;
  parent_instance_number?: number;
  product_relationship?: string;
  product_id?: string;
  product_description?: string;
  product_quantity?: number;
  product_family?: string;
  architecture_group?: string;
  architecture_sub_group?: string;
  item_type?: string;
  network?: string;
  installed_base_status?: string;
  serviceable?: string;
  renewable?: string;
  host_name?: string;
  hardware_list_price?: number;
  maintenance_list_price?: string;
  hardware_bill_to_name?: string;
  ship_to_customer_name?: string;
  best_available_ship_date?: string | Moment;
  shipped_within_5_years?: string;
  gu_id?: number;
  gu_name?: string;
  region?: string;
  business_unit?: string;
  installed_site_id?: number;
  installed_site_name?: string;
  installed_site_address_1?: string;
  installed_site_city?: string;
  installed_site_state?: string;
  installed_site_province?: string;
  installed_site_postal_code?: number;
  installed_site_country?: string;
  covered_line_status?: string;
  coverage_status?: string;
  contract_number?: number;
  contract_bill_to_name?: string;
  contract_bill_to_country?: string;
  service_level?: string;
  service_level_description?: string;
  service_level_category?: string;
  product_coverage_line_number?: string;
  covered_line_start_date?: string | Moment;
  covered_line_end_date?: string | Moment;
  expiration_range?: string;
  termination_date?: number;
  last_date_of_support?: string | Moment;
  l_do_s_category?: string;
  warranty_type?: string;
  warranty_end_date?: string;
  hardware_po_number?: string;
  hardware_so_number?: number;
  maintenance_po_number?: string;
  maintenance_so_number?: string;
  end_of_sale_date?: number;
  end_of_routine_failure_analysis_date?: string;
  end_of_new_service_attachment_date?: string;
  end_of_service_contract_renewal?: string;
  end_of_sig_releases_date?: string;
  end_of_security_support_date?: string;
  end_of_software_availability_date?: string;
  end_of_software_license_availability_date?: string;
  end_of_software_date?: string;
  date_added?: string | Moment;
}

export interface ISearchCiscoIB extends ISearch {
  is_lookup?: boolean;
}
